// Package export renders a rules.json report into the formats people and
// agents read: path-scoped Claude Code rule files, a Claude Code skill, a
// Markdown handbook, and a tier-filtered rules.json.
package export

import (
	"bytes"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"text/template"
	"time"

	"github.com/an4eetos/pr_reviews_to_skills/internal/output"
	"github.com/an4eetos/pr_reviews_to_skills/internal/rules"
	"github.com/an4eetos/pr_reviews_to_skills/internal/store"
)

const (
	FormatClaudeRules = "claude-rules"
	FormatSkill       = "skill"
	FormatManual      = "manual"
	FormatJSON        = "json"
)

var Formats = []string{FormatClaudeRules, FormatSkill, FormatManual, FormatJSON}

// All is what "all" expands to: every rendered format. json, a filtered copy
// of the input, must be asked for by name.
var All = []string{FormatClaudeRules, FormatSkill, FormatManual}

// defaultMinTier is the weakest tier each format includes unless overridden.
// Rule files are always in an agent's context, so they carry only rules to
// follow; the skill adds weaker rules as hints; people get everything.
var defaultMinTier = map[string]rules.Tier{
	FormatClaudeRules: rules.TierConditional,
	FormatSkill:       rules.TierConsider,
	FormatManual:      rules.TierRejected,
	FormatJSON:        rules.TierRejected,
}

// Marker appears in every generated Markdown file. Regeneration only deletes
// prrules-*.md files that carry it, never hand-written ones.
const Marker = "generated by prrules"

const (
	ManualFile   = "PR-REVIEW-HANDBOOK.md"
	rulePrefix   = "prrules-"
	maxSkillName = 64
)

//go:embed templates/*.tmpl
var templateFS embed.FS

var tmpl = template.Must(template.New("").Funcs(template.FuncMap{
	"oneline":    oneLine,
	"yaml":       strconv.Quote,
	"date":       func(t time.Time) string { return t.UTC().Format("2006-01-02") },
	"month":      month,
	"fence":      fence,
	"blockquote": blockquote,
	"category":   CategoryName,
	"anchor":     anchor,
	"tier":       tierName,
	"metrics":    metricsLine,
	"join":       strings.Join,
	"code":       codeList,
	"marker":     func() string { return Marker },
	"conf":       func(f float64) string { return strconv.FormatFloat(f, 'f', 2, 64) },
	"lang":       fenceLang,
}).ParseFS(templateFS, "templates/*.tmpl"))

type Options struct {
	Formats []string
	// Dest is the directory exports are written under (the repo root when the
	// Claude Code files should be picked up directly).
	Dest string
	// MinTier, when set, overrides every format's default weakest tier.
	MinTier rules.Tier
}

// ParseFormats turns "claude-rules,skill" into a validated, deduped list.
func ParseFormats(s string) ([]string, error) {
	var out []string
	for _, f := range strings.Split(s, ",") {
		f = strings.ToLower(strings.TrimSpace(f))
		if f == "" || slices.Contains(out, f) {
			continue
		}
		if f == "all" {
			for _, a := range All {
				if !slices.Contains(out, a) {
					out = append(out, a)
				}
			}
			continue
		}
		if !slices.Contains(Formats, f) {
			return nil, fmt.Errorf("unknown export format %q (want %s or all)", f, strings.Join(Formats, ", "))
		}
		out = append(out, f)
	}
	return out, nil
}

// ParseTier validates a tier name; empty means "use each format's default".
func ParseTier(s string) (rules.Tier, error) {
	if s == "" {
		return "", nil
	}
	t := rules.Tier(strings.ToLower(strings.TrimSpace(s)))
	if !slices.Contains(rules.Tiers, t) {
		return "", fmt.Errorf("unknown tier %q", s)
	}
	return t, nil
}

// Write renders rep in every requested format under opts.Dest and returns
// the files it wrote.
func Write(rep output.Report, opts Options) ([]string, error) {
	var written []string
	for _, f := range opts.Formats {
		min := defaultMinTier[f]
		if opts.MinTier != "" {
			min = opts.MinTier
		}
		d := newDoc(rep, filter(rep.Rules, min))
		var files []string
		var err error
		switch f {
		case FormatClaudeRules:
			files, err = writeClaudeRules(d, opts.Dest)
		case FormatSkill:
			files, err = writeSkill(d, opts.Dest)
		case FormatManual:
			files, err = render(filepath.Join(opts.Dest, ManualFile), "manual.md.tmpl", d)
		case FormatJSON:
			out := rep
			out.Rules = d.Rules
			path := filepath.Join(opts.Dest, "rules.json")
			err = store.WriteJSON(path, out)
			files = []string{path}
		default:
			err = fmt.Errorf("unknown export format %q", f)
		}
		if err != nil {
			return written, fmt.Errorf("export %s: %w", f, err)
		}
		written = append(written, files...)
	}
	return written, nil
}

// Missing reports whether any requested format has never been written under
// dest, so an unchanged rule set still gets exports that were added later.
func Missing(rep output.Report, opts Options) bool {
	for _, f := range opts.Formats {
		var path string
		switch f {
		case FormatClaudeRules:
			path = filepath.Join(opts.Dest, ".claude", "rules")
		case FormatSkill:
			path = filepath.Join(opts.Dest, ".claude", "skills", SkillName(rep), "SKILL.md")
		case FormatManual:
			path = filepath.Join(opts.Dest, ManualFile)
		case FormatJSON:
			path = filepath.Join(opts.Dest, "rules.json")
		}
		if !store.Exists(path) {
			return true
		}
	}
	return false
}

// filter keeps rules at or above min and orders them by tier, category and
// ID rather than confidence, so small score changes between scheduled runs
// don't reshuffle the generated files.
func filter(in []rules.Rule, min rules.Tier) []rules.Rule {
	var out []rules.Rule
	for _, r := range in {
		if r.Tier.Rank() <= min.Rank() {
			out = append(out, r)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		a, b := out[i], out[j]
		if a.Tier.Rank() != b.Tier.Rank() {
			return a.Tier.Rank() < b.Tier.Rank()
		}
		if ca, cb := catRank(a.Category), catRank(b.Category); ca != cb {
			return ca < cb
		}
		return a.ID < b.ID
	})
	return out
}

func catRank(c string) int {
	if i := slices.Index(rules.Categories, c); i >= 0 {
		return i
	}
	return len(rules.Categories)
}

// doc is the data every template sees.
type doc struct {
	output.Report
	Label    string // owner/name, or "N repositories" for a combined set
	Rules    []rules.Rule
	Sections []section
}

type section struct {
	Tier       rules.Tier
	Title      string
	Categories []catGroup
	Rules      []rules.Rule
}

type catGroup struct {
	Category string
	Rules    []rules.Rule
}

var sectionTitles = map[rules.Tier]string{
	rules.TierGolden:      "Always",
	rules.TierConditional: "When the condition holds",
	rules.TierConsider:    "Worth considering (weaker evidence)",
	rules.TierRejected:    "Rejected",
}

func newDoc(rep output.Report, rs []rules.Rule) doc {
	d := doc{Report: rep, Label: rep.Repo, Rules: rs}
	if d.Label == "" {
		d.Label = fmt.Sprintf("%d repositories", len(rep.Repos))
	}
	d.Sections = sections(rs)
	return d
}

// sections groups already-sorted rules by tier, then category.
func sections(rs []rules.Rule) []section {
	var out []section
	for _, r := range rs {
		if len(out) == 0 || out[len(out)-1].Tier != r.Tier {
			out = append(out, section{Tier: r.Tier, Title: sectionTitles[r.Tier]})
		}
		s := &out[len(out)-1]
		s.Rules = append(s.Rules, r)
		if len(s.Categories) == 0 || s.Categories[len(s.Categories)-1].Category != r.Category {
			s.Categories = append(s.Categories, catGroup{Category: r.Category})
		}
		g := &s.Categories[len(s.Categories)-1]
		g.Rules = append(g.Rules, r)
	}
	return out
}

func render(path, name string, data any) ([]string, error) {
	var b bytes.Buffer
	if err := tmpl.ExecuteTemplate(&b, name, data); err != nil {
		return nil, err
	}
	if err := store.WriteFile(path, b.Bytes()); err != nil {
		return nil, err
	}
	return []string{path}, nil
}

// ruleFile is one .claude/rules file: either all repo-wide rules of one
// category, or all rules sharing one set of path globs.
type ruleFile struct {
	doc
	Paths        []string
	Heading      string
	ShowCategory bool
}

func writeClaudeRules(d doc, dest string) ([]string, error) {
	dir := filepath.Join(dest, ".claude", "rules")
	if err := removeStale(dir); err != nil {
		return nil, err
	}
	byCat := map[string][]rules.Rule{}
	byPaths := map[string][]rules.Rule{}
	for _, r := range d.Rules {
		if len(r.Scope.Paths) == 0 {
			byCat[r.Category] = append(byCat[r.Category], r)
			continue
		}
		ps := slices.Clone(r.Scope.Paths)
		sort.Strings(ps)
		key := strings.Join(slices.Compact(ps), "\n")
		byPaths[key] = append(byPaths[key], r)
	}

	var written []string
	emit := func(name string, f ruleFile, rs []rules.Rule) error {
		f.Rules = rs
		f.Sections = sections(rs)
		files, err := render(filepath.Join(dir, name), "claude_rule.md.tmpl", f)
		written = append(written, files...)
		return err
	}
	for _, cat := range rules.Categories {
		if rs := byCat[cat]; len(rs) > 0 {
			f := ruleFile{doc: d, Heading: fmt.Sprintf("%s review rules for %s", CategoryName(cat), d.Label)}
			if err := emit(rulePrefix+cat+".md", f, rs); err != nil {
				return written, err
			}
		}
	}
	keys := make([]string, 0, len(byPaths))
	for k := range byPaths {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	used := map[string]int{}
	for _, k := range keys {
		paths := strings.Split(k, "\n")
		base := output.Slug(strings.Join(paths, " "))
		if base == "" {
			base = "paths"
		}
		used[base]++
		name := rulePrefix + "scoped-" + base
		if n := used[base]; n > 1 {
			name += fmt.Sprintf("-%d", n)
		}
		f := ruleFile{doc: d, Paths: paths, ShowCategory: true,
			Heading: fmt.Sprintf("Review rules for %s in %s", codeList(paths), d.Label)}
		if err := emit(name+".md", f, byPaths[k]); err != nil {
			return written, err
		}
	}
	return written, nil
}

// removeStale deletes generated rule files from a previous export so rules
// that disappeared, or moved to another path set, don't linger.
func removeStale(dir string) error {
	matches, err := filepath.Glob(filepath.Join(dir, rulePrefix+"*.md"))
	if err != nil {
		return err
	}
	for _, m := range matches {
		data, err := os.ReadFile(m)
		if err != nil {
			return err
		}
		if bytes.Contains(data[:min(len(data), 1024)], []byte(Marker)) {
			if err := os.Remove(m); err != nil {
				return err
			}
		}
	}
	return nil
}

type skillDoc struct {
	doc
	Name        string
	Description string
}

func writeSkill(d doc, dest string) ([]string, error) {
	name := SkillName(d.Report)
	sd := skillDoc{doc: d, Name: name, Description: fmt.Sprintf(
		"Code review conventions for %s, mined from what reviewers repeatedly asked for in %d pull requests. "+
			"Use when writing, reviewing or refactoring code in %s, or when asked about its conventions, style or recurring review feedback.",
		d.Label, d.Stats.PRsWithDiscussion, d.Label)}
	dir := filepath.Join(dest, ".claude", "skills", name)
	written, err := render(filepath.Join(dir, "SKILL.md"), "skill.md.tmpl", sd)
	if err != nil {
		return written, err
	}
	more, err := render(filepath.Join(dir, "reference", "evidence.md"), "evidence.md.tmpl", d)
	return append(written, more...), err
}

// SkillName is the skill's directory and frontmatter name: lowercase,
// hyphenated, at most 64 characters.
func SkillName(rep output.Report) string {
	base := "combined"
	if rep.Repo != "" {
		base = output.Slug(strings.ReplaceAll(rep.Repo, "/", "-"))
	}
	const suffix = "-review-rules"
	if len(base) > maxSkillName-len(suffix) {
		base = strings.TrimRight(base[:maxSkillName-len(suffix)], "-")
	}
	return base + suffix
}

var categoryNames = map[string]string{
	"error-handling":    "Error handling",
	"api-design":        "API design",
	"recurring-mistake": "Recurring mistakes",
}

// CategoryName is the human heading for a category slug.
func CategoryName(c string) string {
	if n, ok := categoryNames[c]; ok {
		return n
	}
	if c == "" {
		return "Other"
	}
	return strings.ToUpper(c[:1]) + c[1:]
}

func tierName(t rules.Tier) string {
	s := string(t)
	if s == "" {
		return ""
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }

func month(t time.Time) string {
	if t.IsZero() {
		return "?"
	}
	return t.UTC().Format("2006-01")
}

// fence wraps code in a fence longer than any backtick run inside it.
func fence(lang, code string) string {
	run, longest := 0, 0
	for _, c := range code {
		if c == '`' {
			run++
			longest = max(longest, run)
		} else {
			run = 0
		}
	}
	f := strings.Repeat("`", max(3, longest+1))
	return f + lang + "\n" + strings.TrimRight(code, "\n") + "\n" + f
}

// fenceLang is the code-fence language for a rule's examples: its only
// language, or none when it spans several.
func fenceLang(s rules.Scope) string {
	if len(s.Languages) == 1 {
		return strings.ToLower(s.Languages[0])
	}
	return ""
}

func blockquote(s string) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	for i, l := range lines {
		lines[i] = strings.TrimRight("> "+l, " ")
	}
	return strings.Join(lines, "\n")
}

func codeList(xs []string) string {
	out := make([]string, len(xs))
	for i, x := range xs {
		out[i] = "`" + x + "`"
	}
	return strings.Join(out, ", ")
}

// anchor mirrors GitHub's heading-anchor algorithm for the handbook's TOC.
func anchor(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case r == ' ':
			b.WriteRune('-')
		case r == '-' || r == '_' || ('a' <= r && r <= 'z') || ('0' <= r && r <= '9'):
			b.WriteRune(r)
		}
	}
	return b.String()
}

func metricsLine(m rules.Metrics) string {
	parts := []string{plural(m.DistinctPRs, "PR"), plural(m.DistinctReviewers, "reviewer")}
	if m.DistinctRepos > 1 {
		parts = append(parts, plural(m.DistinctRepos, "repo"))
	}
	if m.MaintainerEndorsed {
		parts = append(parts, "maintainer-endorsed")
	}
	if m.Accepted > 0 {
		parts = append(parts, fmt.Sprintf("%d accepted", m.Accepted))
	}
	if against := m.Disputed + m.Opposing; against > 0 {
		parts = append(parts, fmt.Sprintf("%d pushback", against))
	}
	if !m.FirstSeen.IsZero() {
		if first, last := month(m.FirstSeen), month(m.LastSeen); first == last {
			parts = append(parts, "seen "+first)
		} else {
			parts = append(parts, "seen "+first+" to "+last)
		}
	}
	return strings.Join(parts, " · ")
}

func plural(n int, noun string) string {
	if n == 1 {
		return "1 " + noun
	}
	return fmt.Sprintf("%d %ss", n, noun)
}
